image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      cd django
      python manage.py migrate
      cd ../etl
      python worldbank-population.py
      cd /workspace/bootstrap4_pagination/
      chmod +x ../wait-for-it.sh
    command: |
      source venv/bin/activate
      ./wait-for-it.sh 127.0.0.1:5432 -- python django/manage.py runserver 0.0.0.0:8000
  
ports:
  - port: 8000
    onOpen: open-preview

  # PostgreSQL server
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod